### ISSUE TITLE
segmentation des ménages

### ISSUE THREAD

**Issue by ldubruque** [NassimOuannoughi/CACF#4]
Je cherche les différentes méthodes pour récupérer la segmentation des ménages (dite ancienne segmentation) sous SAS

**Comment by KatellDuchenne** [comment]
Tu trouveras ci-dessous le code qui permet de la récupérer. La première partie du code permet de récupérer l'idmen et la deuxième le seg_men.  

/* RECUP IDMEN */
proc sql;
create table TABLE as
select BASE.* , men.idmen
from BASE a
left join 
sid.clients as men
on a.idcli=men.idcli
;

/*RECUP SEG MEN */
proc sql;
create table TABLE2 as
select a.*,b.seg_men
from TABLE a left join seg.men b
on a.idmen=b.idmen;
quit;
