### ISSUE TITLE
Kantar

### ISSUE THREAD

**Issue by PierreBernardi** [NassimOuannoughi/CACF#5]
Hello Nico, 

Je dois trouver une liste de site internet afin de booster notre prospection sur le Web. 
J'ai des infos sur mes types de clients à préconiser et à éviter.
Peux-tu me poster un petit tuto pour accéder au données Kantar ?

**Comment by nicodiablo** [comment]
C'est prêt :-),

Tu trouveras tout ce qu'il te faut dans le dossier CACF/KANTAR/
